import { ArrowRight, CheckCircle2, CircleHelp, ExternalLink, UserRound, UsersRound, GraduationCap } from 'lucide-react'
import { competitors, competitorUrl, reportUrl, researchDecisions, researchStatus } from '../data/research'
import { useI18n } from '../i18n/context'
import { PageIntro, Reveal, Section, SectionHeading, StatusBadge } from '../components/UI'

export function ResearchPage() {
  const { t } = useI18n()
  return <>
    <PageIntro eyebrow={t('research.eyebrow')} title={t('research.title')} lead={t('research.lead')} tone="green" />
    <Section><Reveal className="report-card"><div><span className="eyebrow">{t('research.reportEyebrow')}</span><h2>{t('research.reportTitle')}</h2><p>{t('research.reportText')}</p><small>{t('research.reportDate')}</small></div><a className="button button-primary" href={reportUrl} target="_blank" rel="noreferrer">{t('research.reportButton')} <ExternalLink size={18} aria-hidden="true" /><span className="sr-only"> ({t('a11y.newTab')})</span></a></Reveal></Section>
    <Section className="surface-section"><div className="research-summary-grid"><Reveal className="summary-panel positive"><CheckCircle2 /><h2>{t('research.suggestsTitle')}</h2><ul>{[1,2,3,4].map(n => <li key={n}>{t(`research.suggests${n}` as never)}</li>)}</ul></Reveal><Reveal className="summary-panel questions"><CircleHelp /><h2>{t('research.testTitle')}</h2><ul>{[1,2,3,4,5].map(n => <li key={n}>{t(`research.test${n}` as never)}</li>)}</ul></Reveal></div></Section>
    <Section><SectionHeading eyebrow={t('research.flowEyebrow')} title={t('research.flowTitle')} lead={t('research.flowLead')} /><div className="decision-accordion">{researchDecisions.map((item, index) => <details key={item.key} className="decision-card" open={index === 0}><summary><span>{String(index + 1).padStart(2,'0')}</span><strong>{t(`research.${item.key}.f` as never)}</strong><StatusPill status={item.featureStatus} t={t} /></summary><div className="decision-chain">{['interpretation','decision','feature','validation'].map((stage, i) => <div key={stage}><small>{t(`research.stage.${stage}` as never)}</small><p>{t(`research.${item.key}.${stage}` as never)}</p>{i < 3 && <ArrowRight aria-hidden="true" />}</div>)}</div></details>)}</div></Section>
    <Section className="surface-section"><SectionHeading title={t('research.ecosystemTitle')} lead={t('research.ecosystemLead')} /><div className="stakeholder-grid">{[[UserRound,'child'],[UsersRound,'parent'],[GraduationCap,'teacher']].map(([Icon,key]) => {const C=Icon as typeof UserRound; return <Reveal key={String(key)} className="stakeholder-card"><C /><h3>{t(`research.${key}.title` as never)}</h3><strong>{t(`research.${key}.role` as never)}</strong><p>{t(`research.${key}.need` as never)}</p></Reveal>})}</div></Section>
    <Section><SectionHeading title={t('research.competitorTitle')} lead={t('research.competitorLead')} /><div className="competitor-grid">{competitors.map(item => <Reveal key={item.name} className="competitor-card"><h3>{item.name}</h3><p>{t(`research.competitor.${item.key}`)}</p><small>{t('research.competitorLimit')}</small></Reveal>)}</div><a className="text-link" href={competitorUrl} target="_blank" rel="noreferrer">{t('research.competitorButton')} <ExternalLink size={16} /><span className="sr-only"> ({t('a11y.newTab')})</span></a></Section>
    <Section className="surface-section"><SectionHeading title={t('research.statusTitle')} lead={t('research.statusLead')} /><div className="status-grid">{researchStatus.map(item => <Reveal key={item.key} className="status-card"><StatusBadge status={item.status} /><h3>{t(`research.status.${item.key}`)}</h3><p>{t(`research.status.${item.key}.note`)}</p></Reveal>)}</div></Section>
  </>
}

function StatusPill({ status, t }: { status: string; t: (key: never) => string }) { return <span className={`feature-status feature-${status}`}>{t(`feature.${status}` as never)}</span> }
